runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT -w 1 main:app
instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 1
  min_instances: 0

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
