runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 5

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
